-- MySQL Script generated by MySQL Workbench
-- Fri Apr  2 10:31:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `biblioteca` ;

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`usuario` (
                                                      `id` INT NOT NULL AUTO_INCREMENT,
                                                      `nombre` VARCHAR(150) NOT NULL,
    `numeroRegistro` VARCHAR(9) NOT NULL,
    `username` VARCHAR(150) NOT NULL,
    `password` VARCHAR(150) NOT NULL,
    `tipo` VARCHAR(25) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 3
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`rol` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `tipoRol` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `tipoRol` (`tipoRol` ASC) VISIBLE)
    ENGINE = InnoDB
    AUTO_INCREMENT = 3
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`autorizacion_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`autorizacion_usuario` (
                                                                   `idUsuario` INT NOT NULL,
                                                                   `idRol` INT NOT NULL,
                                                                   INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
    INDEX `idRol` (`idRol` ASC) VISIBLE,
    CONSTRAINT `autorizacion_usuario_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `biblioteca`.`usuario` (`id`),
    CONSTRAINT `autorizacion_usuario_ibfk_2`
    FOREIGN KEY (`idRol`)
    REFERENCES `biblioteca`.`rol` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`categoria` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `descripcion` VARCHAR(300) NULL DEFAULT NULL,
    `nombre` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 3
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`libro` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `autor` VARCHAR(150) NULL DEFAULT NULL,
    `codigo` VARCHAR(50) NULL DEFAULT NULL,
    `edicion` INT NOT NULL,
    `fechaPublicacion` DATE NULL DEFAULT NULL,
    `idioma` INT NOT NULL,
    `nombre` VARCHAR(200) NOT NULL,
    `pathImagen` LONGBLOB NULL DEFAULT NULL,
    `stock` INT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `codigo` (`codigo` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`prestamo` (
                                                       `id` INT NOT NULL AUTO_INCREMENT,
                                                       `nombre` VARCHAR(200) NOT NULL,
    `apellido` VARCHAR(200) NOT NULL,
    `dpi` VARCHAR(15) NULL DEFAULT NULL,
    `carnet` VARCHAR(11) NULL DEFAULT NULL,
    `carrera` VARCHAR(100) NULL DEFAULT NULL,
    `fechaReservacion` DATE NULL DEFAULT NULL,
    `fechaInicio` DATE NULL DEFAULT NULL,
    `fechaFin` DATE NULL DEFAULT NULL,
    `costo` DOUBLE NULL DEFAULT NULL,
    `estado` VARCHAR(20) NOT NULL,
    `codigoReservacion` VARCHAR(10) NOT NULL,
    `codigoLibro` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `codigoLibro` (`codigoLibro` ASC) VISIBLE,
    CONSTRAINT `prestamo_ibfk_1`
    FOREIGN KEY (`codigoLibro`)
    REFERENCES `biblioteca`.`libro` (`codigo`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`token_autenticacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`token_autenticacion` (
    `id` VARCHAR(200) NOT NULL,
    `ultimoAcceso` DATETIME(6) NOT NULL,
    `idUsuario` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
    CONSTRAINT `token_autenticacion_ibfk_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `biblioteca`.`usuario` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `biblioteca`.`libro_asignado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`libro_asignado` (
                                                             `id` INT NOT NULL AUTO_INCREMENT,
                                                             `idLibro` INT NOT NULL,
                                                             `idCategoria` INT NOT NULL,
                                                             PRIMARY KEY (`id`),
    INDEX `fk_tag_libro1_idx` (`idLibro` ASC) VISIBLE,
    INDEX `fk_tag_categoria1_idx` (`idCategoria` ASC) VISIBLE,
    CONSTRAINT `fk_tag_libro1`
    FOREIGN KEY (`idLibro`)
    REFERENCES `biblioteca`.`libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_tag_categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `biblioteca`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
